### ISSUE TITLE
Breaks rgthree Image Comparer node

### ISSUE THREAD

**Issue by DeepSeaCatz** [get-salt-AI/SaltAI#20]
I'm not sure why, but this custom node breaks the Image Comparer from rgthree by only displaying the image_a and not showing the slider interaction to compare image_b as well :
[https://github.com/rgthree/rgthree-comfy](https://github.com/rgthree/rgthree-comfy)

![image](https://github.com/user-attachments/assets/02a7ecca-0ede-4f60-b3f5-538bbc67fb07)

I have to disable SaltAI node in the manager for it to work again. No idea if this node breaks other custom node.

**Comment by DeepSeaCatz** [comment]
I see that rgthree specific warning is that it fail to load the 2nd image:
`Failed to load resource: the server responded with a status of 404 (Not Found)
:8188/view?filename=rgthree.compare._temp_zcxrz_00002_.png&type=temp&subfolder=&rand=0.5489169325664103:1`

For the full console list, I have many custom nodes, so this is a before after.

### **This is when SaltAI node is disabled:**
app.js:1431 Error loading extension /extensions/ComfyUI-OpenPose-Editor-Plus/openpose.js SyntaxError: missing ) after argument list
(anonymous) @ app.js:1431
app.js:1431 Error loading extension /extensions/ComfyUI-OpenPose-Editor-Plus/fabricnew.min.js TypeError: Cannot read properties of undefined (reading 'fabric')
    at fabricnew.min.js:1:38397
    at fabricnew.min.js:1:50488
(anonymous) @ app.js:1431
:8188/extensions/dzNodes/dz_DZ_widgets.js:1 
        
        
       Failed to load resource: the server responded with a status of 404 (Not Found)
app.js:1431 Error loading extension /extensions/dzNodes/dz_debug.js TypeError: Failed to fetch dynamically imported module: http://127.0.0.1:8188/extensions/dzNodes/dz_debug.js
(anonymous) @ app.js:1431
imageFeed.js:87 [mtb] - Aborting the loading of mtb's imageFeed in favor of pysssss.ImageFeed
init @ imageFeed.js:87
:8188/DZ/debug:1 
        
        
       Failed to load resource: the server responded with a status of 404 (Not Found)
app.js:254 Error calling extension 'DZ.widgets' method 'init' Object Object Object
(anonymous) @ app.js:254
api.js:154 Unhandled message: {"type": "crystools.monitor", "data": {"cpu_utilization": 41.4, "ram_total": 34307997696, "ram_used": 12982607872, "ram_used_percent": 37.8, "hdd_total": 2000396742656, "hdd_used": 1789607456768, "hdd_used_percent": 89.5, "device_type": "cuda", "gpus": [{"gpu_utilization": 46, "gpu_temperature": 55, "vram_total": 25769803776, "vram_used": 2042945536, "vram_used_percent": 7.927672068277995}]}} Error: Unknown message type crystools.monitor
    at WebSocket.<anonymous> (api.js:149:18)
(anonymous) @ api.js:154
jsonToText.js:9 JsonToText
beforeRegisterNodeDef @ jsonToText.js:9
viewText.js:9 ViewText
beforeRegisterNodeDef @ viewText.js:9
playSound.js:7 PlayMusic
beforeRegisterNodeDef @ playSound.js:7
components-manager.js:767 Empty components: policy ignored
rgthree.js:301 [rgthree] Blocked extension 'efficiency.widgethider' method 'nodeCreated' for rgthree-nodes because: Overrides value getter before widget getter is prepared. Can be lifted if/when https://github.com/jags111/efficiency-nodes-comfyui/pull/203 is pulled.
(anonymous) @ rgthree.js:301
linkRenderMode.js:9 [🐍 pysssss] Skipping LinkRenderMode as core extension found
modelInfo.js:307 Object
view:1 
                
       Failed to load resource: the server responded with a status of 404 (Not Found)
view:1         
        
       Failed to load resource: the server responded with a status of 404 (Not Found)
:8188/DZ/debug:1         
        
       Failed to load resource: the server responded with a status of 405 (Method Not Allowed)
:8188/extensions/ComfyUI-Custom-Scripts/js/assets/favicon-active.user.ico:1         
        
       Failed to load resource: the server responded with a status of 404 (Not Found)
:8188/pysssss/autocomplete:1 
                
       Failed to load resource: the server responded with a status of 404 (Not Found)
buttonGroup.js:1         
        
       Failed to load resource: the server responded with a status of 404 (Not Found)
comfyui-manager.js:1364 ComfyUI is outdated. New style menu based features are disabled.
:8188/extensions/ComfyUI-Custom-Scripts/js/assets/favicon.user.ico:1         
        
       Failed to load resource: the server responded with a status of 404 (Not Found)
use_everywhere_utilities.js:134 node_in_loop made 3 checks
prompt_service.js:117 'execution_start' fired before prompt was made.
(anonymous) @ prompt_service.js:117



### **This is when it's enabled:**
app.js:1431 Error loading extension /extensions/ComfyUI-OpenPose-Editor-Plus/fabricnew.min.js TypeError: Cannot read properties of undefined (reading 'fabric')
    at fabricnew.min.js:1:38397
    at fabricnew.min.js:1:50488
(anonymous) @ app.js:1431
app.js:1431 Error loading extension /extensions/ComfyUI-OpenPose-Editor-Plus/openpose.js SyntaxError: missing ) after argument list
(anonymous) @ app.js:1431
:8188/extensions/dzNodes/dz_DZ_widgets.js:1         
        
       Failed to load resource: the server responded with a status of 404 (Not Found)
app.js:1431 Error loading extension /extensions/dzNodes/dz_debug.js TypeError: Failed to fetch dynamically imported module: http://127.0.0.1:8188/extensions/dzNodes/dz_debug.js
(anonymous) @ app.js:1431
imageFeed.js:87 [mtb] - Aborting the loading of mtb's imageFeed in favor of pysssss.ImageFeed
init @ imageFeed.js:87
helpbutton.js:37 Initializing Documentation class for Help
:8188/DZ/debug:1         
        
       Failed to load resource: the server responded with a status of 404 (Not Found)
app.js:254 Error calling extension 'DZ.widgets' method 'init' Object Object Object
(anonymous) @ app.js:254
api.js:154 Unhandled message: {"type": "crystools.monitor", "data": {"cpu_utilization": 44.7, "ram_total": 34307997696, "ram_used": 13132959744, "ram_used_percent": 38.3, "hdd_total": 2000396742656, "hdd_used": 1789607464960, "hdd_used_percent": 89.5, "device_type": "cuda", "gpus": [{"gpu_utilization": 5, "gpu_temperature": 55, "vram_total": 25769803776, "vram_used": 2094510080, "vram_used_percent": 8.127768834431965}]}} Error: Unknown message type crystools.monitor
    at WebSocket.<anonymous> (api.js:149:18)
(anonymous) @ api.js:154
jsonToText.js:9 JsonToText
beforeRegisterNodeDef @ jsonToText.js:9
viewText.js:9 ViewText
beforeRegisterNodeDef @ viewText.js:9
playSound.js:7 PlayMusic
beforeRegisterNodeDef @ playSound.js:7
components-manager.js:767 Empty components: policy ignored
rgthree.js:301 [rgthree] Blocked extension 'efficiency.widgethider' method 'nodeCreated' for rgthree-nodes because: Overrides value getter before widget getter is prepared. Can be lifted if/when https://github.com/jags111/efficiency-nodes-comfyui/pull/203 is pulled.
(anonymous) @ rgthree.js:301
linkRenderMode.js:9 [🐍 pysssss] Skipping LinkRenderMode as core extension found
modelInfo.js:307 Object
:8188/view?filename=rgthree.compare._temp_zcxrz_00001_.png&type=temp&subfolder=&rand=0.9403958754803174:1         
        
       Failed to load resource: the server responded with a status of 404 (Not Found)
:8188/view?filename=rgthree.compare._temp_zcxrz_00002_.png&type=temp&subfolder=&rand=0.5489169325664103:1         
        
       Failed to load resource: the server responded with a status of 404 (Not Found)
:8188/DZ/debug:1         
        
       Failed to load resource: the server responded with a status of 405 (Method Not Allowed)
:8188/extensions/ComfyUI-Custom-Scripts/js/assets/favicon-active.user.ico:1         
        
       Failed to load resource: the server responded with a status of 404 (Not Found)
:8188/pysssss/autocomplete:1         
        
       Failed to load resource: the server responded with a status of 404 (Not Found)
:8188/scripts/ui/components/buttonGroup.js:1         
        
       Failed to load resource: the server responded with a status of 404 (Not Found)
comfyui-manager.js:1364 ComfyUI is outdated. New style menu based features are disabled.
:8188/extensions/ComfyUI-Custom-Scripts/js/assets/favicon.user.ico:1         
        
       Failed to load resource: the server responded with a status of 404 (Not Found)
use_everywhere_utilities.js:134 node_in_loop made 3 checks
prompt_service.js:117 'execution_start' fired before prompt was made.
(anonymous) @ prompt_service.js:117
127.0.0.1/:1 Uncaught (in promise) Error: A listener indicated an asynchronous response by returning true, but the message channel closed before a response was received

**Comment by WAS-PlaiLabs** [comment]
Try disabling the help button: `SaltAI/web/helpbutton.js` to like `SaltAI/web/helpbutton.js.bak`. That's the only JS that could be effecting "any" node (that isn't targeting a specific node)

**Comment by DeepSeaCatz** [comment]
That worked! Not sure what's in the file that cause this issue, but that's a good alternative for now.

Thanks!
